### ISSUE TITLE
Set up basic django app

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/sklDj#3]
- [x] virtualenv
- [x] gitignore (db, bin etc...)
- [x] requirements.txt
- [x] add all basic details for setup to readme.

**Comment by drvinceknight** [comment]
Working on this on branch `3-basicdjangoapp`

**Comment by JasYoung315** [comment]
Needs numpy added to the requirments.txt for sklearn

**Comment by drvinceknight** [comment]
Addressed by #18
