### ISSUE TITLE
Investigate selenium testing on travis

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/sklDj#6]
See #4 and #5

**Comment by JasYoung315** [comment]
[SauceLabs](http://docs.travis-ci.com/user/gui-and-headless-browsers/) seems to be the way to do it but requires a subscription

**Comment by JasYoung315** [comment]
Another way would be to use Xvfb to run headless browser tests according to [this](http://elementalselenium.com/tips/38-headless) guide. 
This is for a server so more investigating needs to be done to make it work on travis.

**Comment by JasYoung315** [comment]
A specific use of Xvfb on travis is found [here](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29)
